### ISSUE TITLE
ipmi remote console support

### ISSUE THREAD

**Issue by setiseta** [bnied/kernel-ml-aufs#1]
Hi,

first of all thx for sharing your nice work.

The only thing is, I'm using your kernel on a remote machine with a ipmi remote console.
If I run you kernel I get a blank screen after grub.
Is it maybe possible to activate ipmi support in this kernel?
Or is there something else wrong?

Kind Regards
Sebastian

**Comment by bnied** [comment]
The IPMI modules are all marked as present:

```
configs-el6/config-4.5.2-x86_64:CONFIG_ACPI_IPMI=m
configs-el6/config-4.5.2-x86_64:CONFIG_IPMI_HANDLER=m
configs-el6/config-4.5.2-x86_64:# CONFIG_IPMI_PANIC_EVENT is not set
configs-el6/config-4.5.2-x86_64:CONFIG_IPMI_DEVICE_INTERFACE=m
configs-el6/config-4.5.2-x86_64:CONFIG_IPMI_SI=m
configs-el6/config-4.5.2-x86_64:# CONFIG_IPMI_SI_PROBE_DEFAULTS is not set
configs-el6/config-4.5.2-x86_64:# CONFIG_IPMI_SSIF is not set
configs-el6/config-4.5.2-x86_64:CONFIG_IPMI_WATCHDOG=m
configs-el6/config-4.5.2-x86_64:CONFIG_IPMI_POWEROFF=m
configs-el7/config-4.5.2-x86_64:CONFIG_ACPI_IPMI=m
configs-el7/config-4.5.2-x86_64:CONFIG_IPMI_HANDLER=m
configs-el7/config-4.5.2-x86_64:# CONFIG_IPMI_PANIC_EVENT is not set
configs-el7/config-4.5.2-x86_64:CONFIG_IPMI_DEVICE_INTERFACE=m
configs-el7/config-4.5.2-x86_64:CONFIG_IPMI_SI=m
configs-el7/config-4.5.2-x86_64:# CONFIG_IPMI_SI_PROBE_DEFAULTS is not set
configs-el7/config-4.5.2-x86_64:# CONFIG_IPMI_SSIF is not set
configs-el7/config-4.5.2-x86_64:CONFIG_IPMI_WATCHDOG=m
configs-el7/config-4.5.2-x86_64:CONFIG_IPMI_POWEROFF=m
```

Which kernel version are you using?

**Comment by setiseta** [comment]
Oh thanks, the problem was the high res mode.
I needed to set "nomodeset" in the /etc/default/grub
if i set it it works, even if its low res, its better than a blank screen.
i don't know how to use it with higher resolutions.
do you have any hints?

**Comment by bnied** [comment]
Does `dmesg` reveal ay IPMI issues?

**Comment by setiseta** [comment]
I can see these 2 error like messages:

```
[    3.353428] ipmi_si IPI0001:00: The BMC does not support clearing the recv irq bit, compensating, but the BMC needs to be fixed.
[    3.369684] ipmi_si IPI0001:00: Error clearing flags: cc
```

But as writen in the post before, its working with nomodeset.
So its ok for me.

thanks for helping.

kind regards

**Comment by bnied** [comment]
Cool. Without more specifics to go off of, I'm guessing it's a BMC incompatibility.
