### ISSUE TITLE
The 4.9.0 can't enable Google TCP-BBR

### ISSUE THREAD

**Issue by xiaoyawl** [bnied/kernel-ml-aufs#2]
I try to open up the Google TCP-BBR optimization algorithm on the 4.9.0 kernel, but the result is a failure, elrepo the ml kernel is possible.
enable:
echo -e "\nnet.core.default_qdisc=fq\nnet.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf && sysctl -p

test:
sysctl net.ipv4.tcp_available_congestion_control
lsmod | grep bbr

**Comment by bnied** [comment]
Yep, looks like the config doesn't have that module enabled:

https://github.com/bnied/kernel-ml-aufs/blob/master/configs-el7/config-4.9.0-x86_64#L918

Changing the config to fix that now.

**Comment by bnied** [comment]
Packages are building now. Will update once they're ready.

**Comment by bnied** [comment]
This should be good to go in `4.9.0-2`:

```
[root@callisto ~]# sysctl net.ipv4.tcp_available_congestion_control
net.ipv4.tcp_available_congestion_control = bbr cubic reno
[root@callisto ~]# lsmod | grep bbr
tcp_bbr                16384  0 
```

**Comment by bnied** [comment]
@xiaoyawl: updated kernel packages are available on both [yum.spaceduck.org](https://yum.spaceduck.org) and [the kernel-ml-aufs Copr repo](https://copr.fedorainfracloud.org/coprs/bnied/kernel-ml-aufs/). Let me know if you see any more issues.

**Comment by xiaoyawl** [comment]
@bnied thank you very much fix this

**Comment by bnied** [comment]
@xiaoyawl you're very welcome. :) Apologies for the delayed response
